# Agent Queue 'Azure Pipelines' was used with unrecognized Agent Specification, vmImage property must be specified to determine image - https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#software
trigger:
  branches:
    include:
    - development

variables:
 buildPlatform: 'AnyCPU'
 buildConfiguration: 'Release'
 solution: '**/IBeam.sln'

steps:
- task: NuGetToolInstaller@1
  name: 'NuGetToolInstaller'
  displayName: 'NuGet Tool Installer'

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '$(project)'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'
