parameters:
- name: solution
  type: string
- name: project
  type: string
- name: packageLocation
  type: string
- name: buildPlatform
  type: string
  default: 'AnyCPU'
- name: buildConfiguration
  type: string
  default: 'Release'
- name: apiKey
  type: string

steps:
- task: NuGetToolInstaller@1
  displayName: 'NuGet Tool Installer'

- task: NuGetCommand@2
  displayName: 'Restore Packages'
  inputs:
    command: 'restore'
    restoreSolution: ${{ parameters.solution }}
    feedsToUse: 'select'

- script: |
    set -e
    dotnet tool install --tool-path . nbgv
    ./nbgv cloud
  displayName: 'NBGV: set version variables'

- task: DotNetCoreCLI@2
  displayName: 'Build Project'
  inputs:
    command: 'build'
    projects: ${{ parameters.project }}
    arguments: '--configuration ${{ parameters.buildConfiguration }}'

- task: DotNetCoreCLI@2
  displayName: 'Create NuGet Package'
  inputs:
    command: 'pack'
    packagesToPack: ${{ parameters.project }}
    packDirectory: '$(Build.ArtifactStagingDirectory)'
    arguments: '--configuration ${{ parameters.buildConfiguration }}'

- script: |
    dotnet nuget push "$(Build.ArtifactStagingDirectory)/**/*.nupkg" \
      --source ${{ parameters.packageLocation }} \
      --api-key ${{ parameters.apiKey }} \
      --skip-duplicate
  displayName: 'Push NuGet Package'
