trigger:
  branches:
    include:
    - main
    - develop
    - feature/*
    - bugfix/*
 tags:
    include:
    - v*
  paths:
    include:
    - IBeam.Services/**
    - .azure-pipelines/templates/**
    - IBeam.sln
    - .azure-pipelines/pipelines.IBeam.Services.Core.nupkg.yml

pool:
  vmImage: 'ubuntu-22.04'

variables:
- group: GitHubNuGetSecrets

- name: buildPlatform
  value: 'AnyCPU'
- name: buildConfiguration
  value: 'Release'
- name: solution
  value: '**/IBeam.sln'
- name: project
  value: '**/IBeam.Services.Core.csproj'
- name: packageLocation
  value: 'https://nuget.pkg.github.com/MedPACTech/index.json'
- name: apiKey
  value: '$(GH_TOKEN)'

stages:
- stage: BuildAndPush
  jobs:
  - job: BuildJob
    steps:
    - checkout: self
      clean: true
      fetchDepth: 0        # NBGV needs full history
      fetchTags: true      # needed for tag-based release versions
      lfs: false

    - template: templates/dotnet-nuget-build.yml
      parameters:
        solution: $(solution)
        project: $(project)
        packageLocation: $(packageLocation)
        apiKey: $(apiKey)
        buildConfiguration: $(buildConfiguration)
