trigger:
  branches:
    include:
    - main
    - development
    - release/*
    - feature/*
    - bugfix/*
  tags:
    include:
    - v*
  paths:
    include:
    - IBeam.Identity/**
    - .azure-pipelines/pipelines.IBeam.Identity.nupkg.yml

pool:
  vmImage: 'ubuntu-22.04'

variables:
- group: GitHubNuGetSecrets

- name: buildPlatform
  value: 'AnyCPU'
- name: buildConfiguration
  value: 'Release'
- name: solution
  value: 'IBeam.sln'
- name: project
  value: '**/IBeam.Identity.csproj'
- name: testProjectPattern
  value: '**/IBeam.Tests.Identity.csproj'
- name: packageLocation
  value: 'https://api.nuget.org/v3/index.json'
- name: apiKey
  value: '$(NUGET_API_KEY)'

stages:
- stage: BuildAndPush
  jobs:
  - job: BuildJob
    steps:
    - checkout: self
      clean: true
      fetchDepth: 0        # NBGV needs full history
      fetchTags: true      # needed for tag-based release versions
      lfs: false

    - template: templates/dotnet-nuget-build.yml
      parameters:
        solution: $(solution)
        project: $(project)
        packageLocation: $(packageLocation)
        apiKey: $(apiKey)
        publishPackages: false
        createPackage: false
        testProjectPattern: $(testProjectPattern)
        buildConfiguration: $(buildConfiguration)






