trigger:
  branches:
    include:
    - main
  paths:
    include:
    - IBeam.Repositories.Scaffold/**
    - .azure-pipelines/templates/**
    - IBeam.sln
    - .azure-pipelines/pipelines.IBeam.Scaffolding.Repositories.nupkg.yml

pool:
  vmImage: 'ubuntu-22.04'

variables:
- group: GitHubNuGetSecrets

- name: buildPlatform
  value: 'AnyCPU'

- name: buildConfiguration
  value: 'Release'

- name: solution
  value: '**/IBeam.sln'

- name: project
  value: '**/IBeam.Scaffolding.Repositories.csproj'

- name: packageLocation
  value: 'https://nuget.pkg.github.com/MedPACTech/index.json'

- name: apiKey
  value: '$(GH_TOKEN)'

stages:
- stage: BuildAndPush
  jobs:
  - job: BuildJob
    steps:
    - template: templates/dotnet-nuget-build.yml
      parameters:
        solution: $(solution)
        project: $(project)
        packageLocation: $(packageLocation)
        apiKey: $(apiKey)
